checkpoint_params:
    checkpoint_path: '/video-conf/scratch/vibhaa_mm_log_directory/pantea1024_hr_skip_connections_augmented_new_layers_alone_trained 17_03_22_16.06.03/00000026-checkpoint.pth.tar'

model_params:
  common_params:
    num_kp: 10
    num_channels: 3
    estimate_jacobian: True
  kp_detector_params:
     temperature: 0.1
     block_expansion: 32
     max_features: 1024
     scale_factor: 0.25
     num_blocks: 5
     run_at_256: True
  generator_params:
    block_expansion: 64
    max_features: 512
    num_down_blocks: 2
    num_bottleneck_blocks: 6
    estimate_occlusion_map: True
    run_at_256: True
    upsample_factor: 4
    use_hr_skip_connections: True
    encode_hr_input_with_additional_blocks: False
    hr_features: 16
    dense_motion_params:
      block_expansion: 64
      max_features: 1024
      num_blocks: 5
      scale_factor: 0.25
      run_at_256: True
